import type { Device, Hazard, Person, Recipient } from "./types";

export const PROJECT_NAME = "示例建设项目";
export const DEMO_WORK_AREA = "示范工区";

export const initialPeople: Person[] = [
  {
    id: "P-001",
    name: "张安全",
    role: "安全员",
    phone: "13800000001",
    gender: "男",
    idCard: "110***********001",
    company: "项目安全管理部",
    workArea: DEMO_WORK_AREA,
    duty: "AI隐患核实、一般隐患复核",
    status: "启用",
    notificationEnabled: true,
  },
  {
    id: "P-002",
    name: "李工区",
    role: "工区负责人",
    phone: "13800000002",
    gender: "男",
    idCard: "110***********002",
    company: "示范工区",
    workArea: DEMO_WORK_AREA,
    duty: "一般隐患整改执行",
    status: "启用",
    notificationEnabled: true,
  },
  {
    id: "P-003",
    name: "王经理",
    role: "项目经理",
    phone: "13800000003",
    gender: "男",
    idCard: "110***********003",
    company: "项目经理部",
    workArea: "全项目",
    duty: "重大隐患接收与最终闭合确认",
    status: "启用",
    notificationEnabled: true,
  },
  {
    id: "P-004",
    name: "赵总监",
    role: "安全总监",
    phone: "17743561681",
    gender: "男",
    idCard: "500***********444",
    company: "项目安全管理部",
    workArea: "全项目",
    duty: "一般隐患接收、重大隐患复核",
    status: "启用",
    notificationEnabled: true,
  },
];

function recipientsFor(level: Hazard["level"], sentAt: string): Recipient[] {
  const roles = level === "重大隐患" ? ["项目经理", "安全总监"] : ["安全总监", "安全员", "工区负责人"];
  return initialPeople
    .filter((person) => roles.includes(person.role))
    .map((person) => ({
      personId: person.id,
      name: person.name,
      role: person.role,
      phone: person.phone,
      status: "模拟已发送",
      sentAt,
    }));
}

export const initialHazards: Hazard[] = [
  {
    id: "YH-20260826-001",
    groupId: "HG-DEMO-001",
    version: 1,
    orderId: "ZGD-20260826-001",
    inspectionId: "XC-20260826-001",
    title: "吊钩防脱装置损坏",
    category: "起重吊装",
    level: "重大隐患",
    status: "待核实",
    project: PROJECT_NAME,
    workArea: DEMO_WORK_AREA,
    point: "塔吊作业面",
    source: "本地上传",
    device: "演示素材-吊装",
    detectedAt: "2026-08-26 09:28",
    deadline: "2026-08-27 09:28",
    evidence: "吊钩卡板未闭合，防脱装置处于无法有效锁闭状态，吊钩本体可见明显磨损。",
    beforeImage: "/hazard-hoist.jpg",
    owner: "王经理",
    verifier: "赵总监",
    repeats: 1,
    isOverdue: false,
    recipients: recipientsFor("重大隐患", "2026-08-26 09:29"),
    rectifications: [],
    timeline: [
      { id: "T-001", title: "AI识别到重大隐患", detail: "系统已保存证据并生成待核实整改单。", time: "2026-08-26 09:28", actor: "AI识别服务", tone: "red" },
      { id: "T-002", title: "整改单自动生成", detail: "ZGD-20260826-001，整改期限24小时。", time: "2026-08-26 09:29", actor: "闭环业务系统", tone: "blue" },
      { id: "T-003", title: "模拟短信已发送", detail: "重大隐患已通知项目经理。", time: "2026-08-26 09:29", actor: "模拟通知服务", tone: "orange" },
    ],
  },
  {
    id: "YH-20260826-002",
    groupId: "HG-DEMO-002",
    version: 1,
    orderId: "ZGD-20260826-002",
    inspectionId: "XC-20260826-001",
    title: "临时用电线路敷设不规范",
    category: "临时用电",
    level: "一般隐患",
    status: "待整改",
    project: PROJECT_NAME,
    workArea: DEMO_WORK_AREA,
    point: "钢筋加工区",
    source: "本地上传",
    device: "演示素材-临时用电",
    detectedAt: "2026-08-26 09:42",
    deadline: "2026-08-29 09:42",
    evidence: "电缆沿地面散乱敷设，未采取架空或穿管保护，人员通行区域存在踩踏与破损风险。",
    beforeImage: "/hazard-electric.jpg",
    owner: "李工区",
    verifier: "张安全",
    repeats: 2,
    isOverdue: false,
    recipients: recipientsFor("一般隐患", "2026-08-26 09:43"),
    rectifications: [],
    timeline: [
      { id: "T-004", title: "AI识别到一般隐患", detail: "系统已生成整改单并自动匹配示范工区。", time: "2026-08-26 09:42", actor: "AI识别服务", tone: "orange" },
      { id: "T-005", title: "模拟通知完成", detail: "已通知安全总监、安全员和示范工区负责人。", time: "2026-08-26 09:43", actor: "模拟通知服务", tone: "blue" },
      { id: "T-006", title: "安全员核实有效", detail: "隐患类别和等级无需调整，正式进入整改。", time: "2026-08-26 10:05", actor: "张安全", tone: "green" },
    ],
  },
  {
    id: "YH-20260825-017",
    groupId: "HG-DEMO-003",
    version: 1,
    orderId: "ZGD-20260825-009",
    inspectionId: "UAV-20260825-003",
    title: "洞口未防护",
    category: "洞口防护",
    level: "重大隐患",
    status: "待整改",
    project: PROJECT_NAME,
    workArea: DEMO_WORK_AREA,
    point: "施工现场地面洞口",
    source: "无人机",
    device: "UAV-02",
    detectedAt: "2026-08-25 16:12",
    deadline: "2026-08-26 16:12",
    evidence: "施工现场地面洞口裸露，未设置有效盖板、护栏或安全网防护，存在人员坠落风险。",
    beforeImage: "/hazard-edge.jpg",
    owner: "王经理",
    verifier: "赵总监",
    repeats: 3,
    isOverdue: false,
    recipients: recipientsFor("重大隐患", "2026-08-25 16:13"),
    rectifications: [],
    timeline: [
      { id: "T-007", title: "重大隐患下发", detail: "项目经理已收到系统通知。", time: "2026-08-25 16:13", actor: "闭环业务系统", tone: "red" },
    ],
  },
  {
    id: "YH-20260824-006",
    groupId: "HG-DEMO-004",
    version: 1,
    orderId: "ZGD-20260824-004",
    inspectionId: "CAM-20260824-018",
    title: "作业人员未规范佩戴安全帽",
    category: "个体防护",
    level: "一般隐患",
    status: "整改中",
    project: PROJECT_NAME,
    workArea: DEMO_WORK_AREA,
    point: "材料堆场",
    source: "摄像头",
    device: "CAM-A1-03",
    detectedAt: "2026-08-24 11:05",
    deadline: "2026-08-27 11:05",
    evidence: "画面中一名作业人员安全帽未系下颌带，存在佩戴不规范情况。",
    beforeImage: "/hazard-ppe.jpg",
    owner: "李工区",
    verifier: "张安全",
    repeats: 5,
    isOverdue: false,
    recipients: recipientsFor("一般隐患", "2026-08-24 11:06"),
    rectifications: [],
    timeline: [
      { id: "T-010", title: "一般隐患自动分发", detail: "安全总监、安全员和工区负责人均已收到模拟短信。", time: "2026-08-24 11:06", actor: "模拟通知服务", tone: "orange" },
    ],
  },
];

export const initialDevices: Device[] = [
  { id: "CAM-A1-03", name: "A1材料堆场摄像头", type: "摄像头", workArea: DEMO_WORK_AREA, point: "材料堆场", status: "在线", aiEnabled: true, lastSeen: "刚刚", streamMode: "RTSP · 子码流" },
  { id: "RTSP-DEMO-01", name: "本地视频循环流", type: "模拟RTSP", workArea: DEMO_WORK_AREA, point: "综合演示点", status: "在线", aiEnabled: true, lastSeen: "5秒前", streamMode: "MediaMTX · 8554" },
  { id: "UAV-02", name: "巡检无人机02", type: "无人机", workArea: DEMO_WORK_AREA, point: "主体结构", status: "任务中", aiEnabled: true, lastSeen: "12秒前", streamMode: "任务文件上传" },
  { id: "DOG-01", name: "四足巡检终端01", type: "机器狗", workArea: DEMO_WORK_AREA, point: "钢筋加工区", status: "离线", aiEnabled: false, lastSeen: "38分钟前", streamMode: "待接入" },
];
